---
ansible:
  verbose: vv
  diff: yes
  config_file: ./ansible.cfg
  host_key_checking: False

vagrant:
  platforms:
    - name: jessie64
      box: debian/jessie64

  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 2048

  instances:
    - name: djangoserver
      ansible_groups:
        - django
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true
      raw_config_args:
        - "vm.network 'forwarded_port', guest: 443, host: 4443"
        - "vm.network 'forwarded_port', guest: 80, host: 8080"
